"""Bob's fighter-motion rows and canonical coverage map.

Bob is a main character and a platform-fighter roster member, so his sheet
covers every applicable category of ``data/fighter_motion_vocabulary.yaml``
(``fighter_core`` and ``generic_item``). Each category resolves to an
authored row; a few categories that are the same silhouette for Bob share
one.

His kit is an engineer's: a big adjustable wrench is his reach, his satchel
holds sealed packets, a telescoping antenna mast is his recovery, and his
analyzer verifies what he receives (the counter). Rows named after those keep
their names in the coverage map so the game can bind them by category.

Every row the procedural Bob published before his SVG redesign keeps its name
(``slash``, ``shoot``, ``wall_slide``, ``hover``, ...), so nothing that bound
the old sheet by row name loses its animation.

Keep this module data-only: ``scripts/build_bob_rig.py`` imports ``BOB_ROWS``
without importing the renderer.
"""

from __future__ import annotations

from typing import Final

#: (row, frames, duration ms). Loops are listed in ``BOB_LOOPS``.
BOB_ROWS: Final[tuple[tuple[str, int, int], ...]] = (
    # Stance / locomotion / traversal.
    ("idle", 8, 140),
    ("idle_side", 8, 150),
    ("idle_front", 8, 150),
    ("idle_look_up", 8, 150),
    ("walk", 8, 105),
    ("walk_stop", 6, 70),
    ("turnaround", 6, 60),
    ("dash_startup", 4, 45),
    ("dash", 6, 60),
    ("run", 8, 72),
    ("stumble", 7, 76),
    ("crouch_start", 4, 50),
    ("crouch", 6, 120),
    ("crouch_walk", 8, 95),
    ("crouch_end", 4, 50),
    ("jump_squat", 4, 40),
    ("jump", 6, 85),
    ("double_jump", 8, 60),
    ("fall", 6, 92),
    ("fall_special", 6, 92),
    ("land", 5, 60),
    ("land_hard", 6, 80),
    ("land_recovery", 6, 70),
    ("tumble", 8, 70),
    ("slide", 6, 70),
    ("roll", 8, 55),
    ("roll_back", 8, 55),
    ("spot_dodge", 6, 50),
    ("air_dodge", 7, 55),
    ("platform_drop", 5, 60),
    ("footstool_jump", 6, 65),
    ("teeter_start", 5, 70),
    ("teeter", 8, 95),
    # Defense / damage / recovery.
    ("shield_raise", 4, 50),
    ("block", 6, 90),
    ("shield_release", 4, 50),
    ("shield_hit", 5, 55),
    ("parry", 7, 55),
    ("hit", 5, 80),
    ("launch", 7, 65),
    ("meteor", 7, 65),
    ("impact", 5, 65),
    ("splat", 7, 80),
    ("ground_bounce", 7, 70),
    ("knockdown", 6, 75),
    ("prone", 8, 110),
    ("prone_damage", 5, 70),
    ("getup", 8, 72),
    ("getup_attack", 9, 60),
    ("getup_roll", 8, 58),
    ("tech", 6, 55),
    ("tech_roll", 7, 55),
    ("wall_tech", 6, 60),
    ("wall_tech_jump", 7, 65),
    ("ceiling_tech", 6, 60),
    ("shield_break_launch", 7, 68),
    ("shield_break_fall", 6, 84),
    ("shield_break_collapse", 8, 82),
    ("shield_break_recover", 8, 86),
    ("dizzy", 10, 96),
    ("sleep_start", 7, 86),
    ("sleep", 10, 130),
    ("wake", 8, 86),
    ("bury_start", 7, 80),
    ("buried", 8, 108),
    ("bury_escape", 8, 72),
    ("death", 10, 100),
    # Normals: a three-hit wrench string, tilts, the dash attack.
    ("jab", 7, 46),
    ("jab_2", 7, 46),
    ("jab_3", 10, 54),
    ("dash_attack", 9, 58),
    ("attack_side", 8, 54),
    ("slash", 8, 56),
    ("attack_up", 9, 54),
    ("attack_down", 7, 50),
    # Smashes: each with its own held charge.
    ("smash_forward_charge", 6, 70),
    ("smash_forward", 11, 56),
    ("smash_up_charge", 6, 70),
    ("smash_up", 10, 56),
    ("smash_down_charge", 6, 70),
    ("smash_down", 11, 54),
    # Aerials.
    ("air_neutral", 8, 52),
    ("air_forward", 9, 56),
    ("air_back", 8, 54),
    ("air_up", 8, 52),
    ("air_down", 9, 60),
    ("air_land", 5, 55),
    ("stomp", 7, 60),
    # Specials: packet toss, torque rush, antenna launch, receive (+ its
    # counter), and the full-handshake final smash.
    ("packet_toss", 10, 60),
    ("torque_rush", 11, 56),
    ("antenna_launch", 11, 58),
    ("receive", 10, 62),
    ("receive_counter", 9, 56),
    ("full_handshake", 16, 74),
    # Grab / throw / victim reactions.
    ("grab", 7, 56),
    ("grab_hold", 8, 92),
    ("pummel", 5, 52),
    ("grab_release", 5, 60),
    ("throw_forward", 9, 58),
    ("throw_back", 9, 60),
    ("throw_up", 9, 60),
    ("throw_down", 9, 60),
    ("grabbed", 8, 88),
    ("grabbed_pummel", 5, 62),
    ("grab_escape", 7, 64),
    # Ledge / wall / climbing / water.
    ("wall_grab", 6, 100),
    ("wall_slide", 6, 80),
    ("wall_jump", 6, 75),
    ("ledge_catch", 5, 62),
    ("ledge_grab", 6, 96),
    ("ledge_getup", 7, 72),
    ("ledge_climb", 6, 92),
    ("ledge_getup_attack", 8, 62),
    ("ledge_roll", 8, 58),
    ("ledge_jump", 7, 66),
    ("ledge_drop", 5, 62),
    ("climb", 8, 96),
    ("swim", 8, 102),
    ("hover", 6, 90),
    ("float_glide", 8, 90),
    # Held items (the item itself is attached at runtime, in the far hand).
    ("item_hold", 8, 108),
    ("item_hold_crouch", 8, 96),
    ("pickup", 7, 66),
    ("item_heavy_pickup", 8, 82),
    ("item_heavy_carry", 8, 102),
    ("throw", 7, 60),
    ("item_drop", 5, 58),
    ("item_swing", 8, 58),
    # Gadgets (the procedural Bob's rows, kept by name).
    ("aim", 6, 90),
    ("shoot", 7, 58),
    ("charge", 8, 80),
    ("cast", 8, 72),
    ("blink_out", 6, 60),
    ("blink_in", 6, 60),
    # Presentation / interaction.
    ("entrance", 12, 84),
    ("celebrate", 10, 90),
    ("victory_hold", 8, 118),
    ("loss", 8, 112),
    ("taunt", 10, 90),
    ("talk", 8, 104),
    ("interact", 8, 92),
    ("sit", 8, 140),
)

#: Rows drawn from Bob's FRONT view (``data/characters/bob/bob_front.svg``,
#: its own rig ``rigged/bob/bob_front.rig.json``); every other row is the
#: side view. The game shows him facing the viewer when he stands and talks.
BOB_FRONT_ROWS: Final[frozenset[str]] = frozenset({"idle_front"})

#: Rows that loop (the rest play once and hold their last frame).
BOB_LOOPS: Final[frozenset[str]] = frozenset({
    "idle", "idle_side", "idle_front", "idle_look_up", "walk", "dash", "run", "crouch", "crouch_walk",
    "fall", "fall_special", "tumble", "teeter", "block", "prone", "dizzy", "sleep", "buried",
    "smash_forward_charge", "smash_up_charge", "smash_down_charge", "grab_hold", "grabbed",
    "wall_grab", "wall_slide", "ledge_grab", "climb", "swim", "hover", "float_glide",
    "item_hold", "item_hold_crouch", "item_heavy_carry", "aim", "charge", "victory_hold", "loss",
    "talk", "interact", "sit", "shield_break_fall",
})

FIGHTER_MOTION_COVERAGE: Final[dict[str, str]] = {
    "idle": "idle",
    "idle_look_up": "idle_look_up",
    "walk": "walk",
    "locomotion_stop": "walk_stop",
    "turnaround": "turnaround",
    "dash_startup": "dash_startup",
    "run": "run",
    "stumble": "stumble",
    "crouch_start": "crouch_start",
    "crouch": "crouch",
    "crouch_walk": "crouch_walk",
    "crouch_jump": "jump",
    "crouch_end": "crouch_end",
    "land_light": "land",
    "land_hard": "land_hard",
    "jump_squat": "jump_squat",
    "jump": "jump",
    "double_jump": "double_jump",
    "fall": "fall",
    "fall_special": "fall_special",
    "land_special": "land_recovery",
    "tumble": "tumble",
    "shield_raise": "shield_raise",
    "shield_hold": "block",
    "shield_release": "shield_release",
    "parry": "parry",
    "shield_hit": "shield_hit",
    "spot_dodge": "spot_dodge",
    "roll_forward": "roll",
    "roll_backward": "roll_back",
    "air_dodge": "air_dodge",
    "jab": "jab",
    "dash_attack": "dash_attack",
    "attack_side": "attack_side",
    "attack_up": "attack_up",
    "attack_down": "attack_down",
    "smash_charge_forward": "smash_forward_charge",
    "smash_forward": "smash_forward",
    "smash_charge_up": "smash_up_charge",
    "smash_up": "smash_up",
    "smash_charge_down": "smash_down_charge",
    "smash_down": "smash_down",
    "air_neutral": "air_neutral",
    "air_forward": "air_forward",
    "air_back": "air_back",
    "air_up": "air_up",
    "air_down": "air_down",
    "air_land": "air_land",
    "special_neutral": "packet_toss",
    "special_side": "torque_rush",
    "special_up": "antenna_launch",
    "special_down": "receive",
    "final_smash": "full_handshake",
    "grab": "grab",
    "grab_hold": "grab_hold",
    "pummel": "pummel",
    "grab_release": "grab_release",
    "throw_forward": "throw_forward",
    "throw_back": "throw_back",
    "throw_up": "throw_up",
    "throw_down": "throw_down",
    "grabbed": "grabbed",
    "grabbed_pummel": "grabbed_pummel",
    "grab_escape": "grab_escape",
    "hit": "hit",
    "launch": "launch",
    "meteor": "meteor",
    "impact": "impact",
    "splat": "splat",
    "ground_bounce": "ground_bounce",
    "prone": "prone",
    "prone_damage": "prone_damage",
    "getup": "getup",
    "getup_attack": "getup_attack",
    "getup_roll": "getup_roll",
    "knockdown": "knockdown",
    "tech": "tech",
    "tech_roll": "tech_roll",
    "wall_tech": "wall_tech",
    "wall_tech_jump": "wall_tech_jump",
    "ceiling_tech": "ceiling_tech",
    "shield_break_launch": "shield_break_launch",
    "shield_break_fall": "shield_break_fall",
    "shield_break_collapse": "shield_break_collapse",
    "shield_break_recover": "shield_break_recover",
    "dizzy": "dizzy",
    "sleep_start": "sleep_start",
    "sleep": "sleep",
    "wake": "wake",
    "bury_start": "bury_start",
    "buried": "buried",
    "bury_escape": "bury_escape",
    "footstool_jump": "footstool_jump",
    "footstooled": "stumble",
    "platform_drop": "platform_drop",
    "teeter_start": "teeter_start",
    "teeter": "teeter",
    "lose_footing": "stumble",
    "ledge_catch": "ledge_catch",
    "ledge_hang": "ledge_grab",
    "ledge_getup": "ledge_getup",
    "ledge_attack": "ledge_getup_attack",
    "ledge_roll": "ledge_roll",
    "ledge_jump": "ledge_jump",
    "ledge_drop": "ledge_drop",
    "trip_fall": "knockdown",
    "trip_land": "ground_bounce",
    "trip_idle": "prone",
    "trip_getup": "getup",
    "trip_attack": "getup_attack",
    "trip_roll": "getup_roll",
    "taunt": "taunt",
    "entrance": "entrance",
    "victory": "celebrate",
    "victory_hold": "victory_hold",
    "loss": "loss",
    "item_hold": "item_hold",
    "item_hold_crouch": "item_hold_crouch",
    "item_pickup": "pickup",
    "item_grip": "item_hold",
    "item_heavy_pickup": "item_heavy_pickup",
    "item_heavy_carry": "item_heavy_carry",
    "item_throw": "throw",
    "item_drop": "item_drop",
    "item_swing": "item_swing",
}

APPLICABLE_MOTION_SCOPES: Final[tuple[str, ...]] = ("fighter_core", "generic_item")

#: Standard categories whose row carries Bob's own name for the move.
EFFECT_ALIASES: Final[dict[str, str]] = {
    "special_neutral": "packet_toss",
    "special_side": "torque_rush",
    "special_up": "antenna_launch",
    "special_down": "receive",
    "final_smash": "full_handshake",
}

__all__ = [
    "APPLICABLE_MOTION_SCOPES",
    "BOB_FRONT_ROWS",
    "BOB_LOOPS",
    "BOB_ROWS",
    "EFFECT_ALIASES",
    "FIGHTER_MOTION_COVERAGE",
]
