"""The goblin's fighter-motion rows and canonical coverage map.

The goblin is a scrappy, cowardly-aggressive little melee fighter: jittery,
hunched, all elbows and teeth. Its moves are the generator's
(``goblin_side.SideGoblinGenerator``) key poses in ``_goblin_moves.py``;
this module is the data the sheet, the game and the tests share.

Every applicable category of ``data/fighter_motion_vocabulary.yaml``
(``fighter_core`` and ``generic_item``) resolves to a row. A goblin's kit is
smaller than a main character's, so more categories share a row (one charge
for all three smashes; the trip reactions are the knockdown family).

The rows the generator published before this moveset keep their names,
frame counts and durations (``LEGACY_ROWS``), so every config and binding
that read them still lines up.

Specials: rock toss (neutral), shiv lunge (side), spring pounce (up), play
dead (down: a counter, a fake death that ends in a stab, ``play_dead_strike``),
and the goblin frenzy (final smash).
"""

from __future__ import annotations

from typing import Final

#: The rows (and their timing) the generator published before this moveset.
LEGACY_ROWS: Final[tuple[tuple[str, int, int], ...]] = (
    ("idle", 8, 120),
    ("walk", 8, 95),
    ("run", 8, 75),
    ("jump", 6, 95),
    ("fall", 6, 95),
    ("slash", 7, 75),
    ("hit", 5, 90),
    ("death", 8, 110),
    ("blink_out", 6, 62),
    ("blink_in", 6, 62),
    ("dash", 6, 65),
    ("talk", 8, 110),
    ("interact", 6, 90),
    ("celebrate", 8, 92),
    ("block", 6, 85),
)

#: (row, frames, duration ms), legacy rows first in their old order.
GOBLIN_ROWS: Final[tuple[tuple[str, int, int], ...]] = LEGACY_ROWS + (
    # Stance / locomotion / traversal.
    ("walk_stop", 5, 70),
    ("turnaround", 5, 60),
    ("dash_startup", 4, 45),
    ("stumble", 6, 70),
    ("crouch_start", 3, 50),
    ("crouch", 6, 110),
    ("crouch_walk", 8, 90),
    ("crouch_end", 3, 50),
    ("jump_squat", 3, 45),
    ("double_jump", 7, 60),
    ("fall_special", 6, 90),
    ("land", 4, 60),
    ("land_hard", 6, 75),
    ("tumble", 8, 65),
    ("roll", 7, 55),
    ("roll_back", 7, 55),
    ("spot_dodge", 6, 50),
    ("air_dodge", 6, 55),
    ("platform_drop", 4, 60),
    ("footstool_jump", 5, 65),
    ("teeter", 8, 90),
    # Defense / damage / recovery.
    ("shield_raise", 3, 50),
    ("shield_release", 3, 50),
    ("shield_hit", 4, 55),
    ("parry", 6, 55),
    ("launch", 6, 65),
    ("meteor", 6, 65),
    ("splat", 6, 75),
    ("ground_bounce", 6, 70),
    ("knockdown", 6, 75),
    ("prone", 8, 110),
    ("prone_damage", 4, 70),
    ("getup", 7, 70),
    ("getup_attack", 8, 60),
    ("getup_roll", 7, 58),
    ("tech", 5, 55),
    ("wall_tech", 5, 60),
    ("dizzy", 10, 96),
    ("sleep", 8, 130),
    ("wake", 6, 80),
    ("bury_start", 6, 70),
    ("buried", 8, 100),
    ("bury_escape", 6, 70),
    # Normals: a stabbing jab string, tilts, the dash attack.
    ("jab", 6, 50),
    ("jab_2", 6, 50),
    ("jab_3", 10, 50),
    ("dash_attack", 8, 58),
    ("attack_up", 8, 55),
    ("attack_down", 7, 50),
    # Smashes (one shared charge).
    ("smash_charge", 6, 70),
    ("smash_forward", 10, 56),
    ("smash_up", 9, 56),
    ("smash_down", 9, 56),
    # Aerials.
    ("air_neutral", 7, 52),
    ("air_forward", 8, 55),
    ("air_back", 7, 52),
    ("air_up", 7, 52),
    ("air_down", 8, 60),
    ("air_land", 4, 55),
    # Specials.
    ("rock_toss", 9, 60),
    ("shiv_lunge", 9, 56),
    ("spring_pounce", 9, 58),
    ("play_dead", 10, 70),
    ("play_dead_strike", 8, 56),
    ("goblin_frenzy", 14, 70),
    # Grab / throw / victim reactions.
    ("grab", 6, 56),
    ("grab_hold", 6, 90),
    ("pummel", 5, 52),
    ("grab_release", 4, 60),
    ("throw_forward", 8, 60),
    ("throw_back", 8, 60),
    ("throw_up", 8, 60),
    ("throw_down", 8, 60),
    ("grabbed", 6, 88),
    ("grabbed_pummel", 4, 62),
    ("grab_escape", 6, 64),
    # Ledge / wall.
    ("ledge_catch", 4, 62),
    ("ledge_grab", 6, 96),
    ("ledge_getup", 6, 72),
    ("ledge_attack", 7, 62),
    ("ledge_roll", 7, 58),
    ("ledge_jump", 6, 66),
    ("ledge_drop", 4, 62),
    ("wall_jump", 5, 70),
    # Held items (the item is attached at runtime, in the far hand).
    ("item_hold", 8, 108),
    ("item_pickup", 6, 66),
    ("item_heavy_pickup", 7, 80),
    ("item_heavy_carry", 8, 100),
    ("item_throw", 6, 60),
    ("item_drop", 4, 58),
    ("item_swing", 7, 58),
    # Presentation.
    ("taunt", 10, 90),
    ("entrance", 10, 84),
    ("victory_hold", 8, 118),
    ("loss", 8, 112),
)

#: Rows that loop.
GOBLIN_LOOPS: Final[frozenset[str]] = frozenset({
    "idle", "walk", "run", "dash", "talk", "interact", "block", "crouch", "crouch_walk", "fall", "fall_special",
    "tumble", "teeter", "prone", "dizzy", "sleep", "buried", "smash_charge", "grab_hold", "grabbed", "ledge_grab",
    "item_hold", "item_heavy_carry", "victory_hold", "loss",
})

FIGHTER_MOTION_COVERAGE: Final[dict[str, str]] = {
    "idle": "idle",
    "idle_look_up": "talk",
    "walk": "walk",
    "locomotion_stop": "walk_stop",
    "turnaround": "turnaround",
    "dash_startup": "dash_startup",
    "run": "run",
    "stumble": "stumble",
    "crouch_start": "crouch_start",
    "crouch": "crouch",
    "crouch_walk": "crouch_walk",
    "crouch_jump": "jump",
    "crouch_end": "crouch_end",
    "land_light": "land",
    "land_hard": "land_hard",
    "jump_squat": "jump_squat",
    "jump": "jump",
    "double_jump": "double_jump",
    "fall": "fall",
    "fall_special": "fall_special",
    "land_special": "land_hard",
    "tumble": "tumble",
    "shield_raise": "shield_raise",
    "shield_hold": "block",
    "shield_release": "shield_release",
    "parry": "parry",
    "shield_hit": "shield_hit",
    "spot_dodge": "spot_dodge",
    "roll_forward": "roll",
    "roll_backward": "roll_back",
    "air_dodge": "air_dodge",
    "jab": "jab",
    "dash_attack": "dash_attack",
    "attack_side": "slash",
    "attack_up": "attack_up",
    "attack_down": "attack_down",
    "smash_charge_forward": "smash_charge",
    "smash_forward": "smash_forward",
    "smash_charge_up": "smash_charge",
    "smash_up": "smash_up",
    "smash_charge_down": "smash_charge",
    "smash_down": "smash_down",
    "air_neutral": "air_neutral",
    "air_forward": "air_forward",
    "air_back": "air_back",
    "air_up": "air_up",
    "air_down": "air_down",
    "air_land": "air_land",
    "special_neutral": "rock_toss",
    "special_side": "shiv_lunge",
    "special_up": "spring_pounce",
    "special_down": "play_dead",
    "final_smash": "goblin_frenzy",
    "grab": "grab",
    "grab_hold": "grab_hold",
    "pummel": "pummel",
    "grab_release": "grab_release",
    "throw_forward": "throw_forward",
    "throw_back": "throw_back",
    "throw_up": "throw_up",
    "throw_down": "throw_down",
    "grabbed": "grabbed",
    "grabbed_pummel": "grabbed_pummel",
    "grab_escape": "grab_escape",
    "hit": "hit",
    "launch": "launch",
    "meteor": "meteor",
    "impact": "splat",
    "splat": "splat",
    "ground_bounce": "ground_bounce",
    "prone": "prone",
    "prone_damage": "prone_damage",
    "getup": "getup",
    "getup_attack": "getup_attack",
    "getup_roll": "getup_roll",
    "knockdown": "knockdown",
    "tech": "tech",
    "tech_roll": "getup_roll",
    "wall_tech": "wall_tech",
    "wall_tech_jump": "wall_jump",
    "ceiling_tech": "tech",
    "shield_break_launch": "launch",
    "shield_break_fall": "fall_special",
    "shield_break_collapse": "knockdown",
    "shield_break_recover": "dizzy",
    "dizzy": "dizzy",
    "sleep_start": "knockdown",
    "sleep": "sleep",
    "wake": "wake",
    "bury_start": "bury_start",
    "buried": "buried",
    "bury_escape": "bury_escape",
    "footstool_jump": "footstool_jump",
    "footstooled": "stumble",
    "platform_drop": "platform_drop",
    "teeter_start": "teeter",
    "teeter": "teeter",
    "lose_footing": "stumble",
    "ledge_catch": "ledge_catch",
    "ledge_hang": "ledge_grab",
    "ledge_getup": "ledge_getup",
    "ledge_attack": "ledge_attack",
    "ledge_roll": "ledge_roll",
    "ledge_jump": "ledge_jump",
    "ledge_drop": "ledge_drop",
    "trip_fall": "knockdown",
    "trip_land": "ground_bounce",
    "trip_idle": "prone",
    "trip_getup": "getup",
    "trip_attack": "getup_attack",
    "trip_roll": "getup_roll",
    "taunt": "taunt",
    "entrance": "entrance",
    "victory": "celebrate",
    "victory_hold": "victory_hold",
    "loss": "loss",
    "item_hold": "item_hold",
    "item_hold_crouch": "crouch",
    "item_pickup": "item_pickup",
    "item_grip": "item_hold",
    "item_heavy_pickup": "item_heavy_pickup",
    "item_heavy_carry": "item_heavy_carry",
    "item_throw": "item_throw",
    "item_drop": "item_drop",
    "item_swing": "item_swing",
}

APPLICABLE_MOTION_SCOPES: Final[tuple[str, ...]] = ("fighter_core", "generic_item")

#: Standard categories whose row carries the goblin's own name for the move.
EFFECT_ALIASES: Final[dict[str, str]] = {
    "special_neutral": "rock_toss",
    "special_side": "shiv_lunge",
    "special_up": "spring_pounce",
    "special_down": "play_dead",
    "final_smash": "goblin_frenzy",
}

__all__ = [
    "APPLICABLE_MOTION_SCOPES",
    "EFFECT_ALIASES",
    "FIGHTER_MOTION_COVERAGE",
    "GOBLIN_LOOPS",
    "GOBLIN_ROWS",
    "LEGACY_ROWS",
]
