"""Carl Stargan fighter-motion rows and current-art coverage.

The complete future vocabulary lives in ``data/fighter_motion_vocabulary.yaml``.
This profile supplies one real row for every currently applicable fighter and
generic-item category while preserving Carl's existing cosmic signature moves.
Fine-grained left/right and grounded/aerial variants may share a row until the
art is strong enough to justify separate choreography.
"""

from __future__ import annotations

from typing import Final


APPLICABLE_MOTION_SCOPES: Final[tuple[str, ...]] = (
    "fighter_core",
    "generic_item",
)


CARL_ROWS: Final[tuple[tuple[str, int, int], ...]] = (
    # Stance / locomotion / traversal.
    ("idle", 8, 150),
    ("idle_look_up", 8, 150),
    ("walk", 8, 108),
    ("walk_stop", 6, 76),
    ("turnaround", 6, 74),
    ("dash_startup", 4, 52),
    ("dash", 6, 62),
    ("run", 8, 82),
    ("stumble", 6, 78),
    ("crouch_start", 5, 72),
    ("crouch", 6, 96),
    ("crouch_walk", 8, 90),
    ("crouch_end", 5, 72),
    ("land_light", 5, 68),
    ("land_hard", 8, 92),
    ("land_recovery", 6, 74),
    ("jump_squat", 5, 60),
    ("jump", 6, 92),
    ("double_jump", 7, 78),
    ("fall", 6, 92),
    ("fall_special", 7, 96),
    ("tumble", 8, 74),
    ("cosmic_drift", 8, 58),
    ("slide", 6, 70),
    ("roll", 8, 58),
    ("roll_back", 8, 58),
    ("spot_dodge", 7, 56),
    ("air_dodge", 7, 60),
    ("platform_drop", 5, 62),
    ("footstool_jump", 6, 68),
    ("teeter_start", 5, 72),
    ("teeter", 8, 96),
    # Defense / damage / recovery.
    ("shield_raise", 5, 62),
    ("block", 6, 84),
    ("shield_release", 5, 62),
    ("parry", 6, 60),
    ("shield_hit", 5, 60),
    ("hit", 5, 88),
    ("launch", 7, 68),
    ("meteor", 7, 68),
    ("impact", 5, 66),
    ("splat", 8, 82),
    ("ground_bounce", 7, 72),
    ("knockdown", 7, 78),
    ("prone", 8, 112),
    ("prone_damage", 5, 72),
    ("getup", 8, 74),
    ("getup_attack", 8, 64),
    ("getup_roll", 8, 60),
    ("tech", 6, 56),
    ("tech_roll", 7, 56),
    ("wall_tech", 6, 62),
    ("wall_tech_jump", 7, 66),
    ("ceiling_tech", 6, 62),
    ("shield_break_launch", 7, 68),
    ("shield_break_fall", 7, 84),
    ("shield_break_collapse", 8, 82),
    ("shield_break_recover", 8, 86),
    ("dizzy", 10, 98),
    ("sleep_start", 7, 86),
    ("sleep", 8, 132),
    ("wake", 8, 86),
    ("bury_start", 7, 80),
    ("buried", 8, 108),
    ("bury_escape", 8, 72),
    # Normals / smashes / aerials.
    ("jab", 5, 58),
    ("punch", 7, 70),
    ("dash_attack", 7, 62),
    ("planetary_orbit", 9, 72),
    ("attack_up", 8, 66),
    ("attack_down", 8, 66),
    ("smash_charge", 8, 84),
    ("smash_forward", 9, 66),
    ("smash_up", 9, 66),
    ("smash_down", 9, 68),
    ("air_neutral", 8, 62),
    ("air_forward", 7, 62),
    ("air_back", 7, 62),
    ("air_down", 7, 70),
    ("air_up", 7, 62),
    ("air_land", 6, 64),
    # Carl-specific abilities used by the Smash special slots.
    ("pale_blue_dot", 9, 78),
    ("cosmic_calendar", 10, 78),
    ("billions_and_billions", 10, 76),
    ("starstuff", 10, 76),
    ("float_glide", 8, 108),
    # Grab / throw / victim reactions.
    ("grab", 7, 62),
    ("grab_hold", 8, 92),
    ("pummel", 5, 58),
    ("grab_release", 5, 62),
    ("throw_forward", 8, 64),
    ("throw_back", 8, 66),
    ("throw_up", 8, 66),
    ("throw_down", 8, 68),
    ("grabbed", 8, 88),
    ("grabbed_pummel", 5, 62),
    ("grab_escape", 7, 66),
    # Wall / ledge / trip.
    ("wall_grab", 6, 105),
    ("wall_jump", 6, 82),
    ("ledge_catch", 5, 64),
    ("ledge_grab", 6, 98),
    ("ledge_getup", 6, 44),
    ("ledge_attack", 8, 66),
    ("ledge_roll", 8, 40),
    ("ledge_jump", 7, 68),
    ("ledge_drop", 5, 62),
    ("ledge_climb", 6, 98),
    ("climb", 8, 98),
    ("swim", 8, 104),
    ("trip_fall", 7, 74),
    ("trip_idle", 8, 108),
    ("trip_getup", 8, 74),
    ("trip_attack", 8, 64),
    ("trip_roll", 8, 60),
    # Generic held-item body motion. Items remain runtime supplied.
    ("item_hold", 8, 108),
    ("item_hold_crouch", 8, 96),
    ("item_pickup", 7, 72),
    ("item_heavy_pickup", 8, 84),
    ("item_heavy_carry", 8, 104),
    ("item_throw", 7, 64),
    ("item_drop", 5, 60),
    ("item_swing", 7, 64),
    # Existing presentation / interaction rows.
    ("talk", 8, 108),
    ("interact", 8, 92),
    ("think", 8, 112),
    ("use_telescope", 10, 96),
    ("stargaze", 10, 108),
    ("taunt", 8, 94),
    ("entrance", 10, 90),
    ("celebrate", 8, 90),
    ("victory_hold", 8, 118),
    ("loss", 8, 114),
    ("death", 8, 108),
)


FIGHTER_MOTION_COVERAGE: Final[dict[str, str]] = {
    "idle": "idle",
    "idle_look_up": "idle_look_up",
    "walk": "walk",
    "locomotion_stop": "walk_stop",
    "turnaround": "turnaround",
    "dash_startup": "dash_startup",
    "run": "run",
    "stumble": "stumble",
    "crouch_start": "crouch_start",
    "crouch": "crouch",
    "crouch_walk": "crouch_walk",
    # Covered by the plain jump until this fighter draws one of their own —
    # several categories resolving to one row is how the catalog keeps a slot
    # open without demanding the art up front.
    "crouch_jump": "jump",
    "crouch_end": "crouch_end",
    "land_light": "land_light",
    "land_hard": "land_hard",
    "jump_squat": "jump_squat",
    "jump": "jump",
    "double_jump": "double_jump",
    "fall": "fall",
    "fall_special": "fall_special",
    "land_special": "land_hard",
    "tumble": "tumble",
    "shield_raise": "shield_raise",
    "shield_hold": "block",
    "shield_release": "shield_release",
    "parry": "parry",
    "shield_hit": "shield_hit",
    "spot_dodge": "spot_dodge",
    "roll_forward": "roll",
    "roll_backward": "roll_back",
    "air_dodge": "air_dodge",
    "jab": "jab",
    "dash_attack": "dash_attack",
    "attack_side": "planetary_orbit",
    "attack_up": "attack_up",
    "attack_down": "attack_down",
    "smash_charge_forward": "smash_charge",
    "smash_forward": "smash_forward",
    "smash_charge_up": "smash_charge",
    "smash_up": "smash_up",
    "smash_charge_down": "smash_charge",
    "smash_down": "smash_down",
    "air_neutral": "air_neutral",
    "air_forward": "air_forward",
    "air_back": "air_back",
    "air_up": "air_up",
    "air_down": "air_down",
    "air_land": "air_land",
    "special_neutral": "pale_blue_dot",
    "special_side": "cosmic_calendar",
    "special_up": "cosmic_drift",
    "special_down": "billions_and_billions",
    "final_smash": "starstuff",
    "grab": "grab",
    "grab_hold": "grab_hold",
    "pummel": "pummel",
    "grab_release": "grab_release",
    "throw_forward": "throw_forward",
    "throw_back": "throw_back",
    "throw_up": "throw_up",
    "throw_down": "throw_down",
    "grabbed": "grabbed",
    "grabbed_pummel": "grabbed_pummel",
    "grab_escape": "grab_escape",
    "hit": "hit",
    "launch": "launch",
    "meteor": "meteor",
    "impact": "impact",
    "splat": "splat",
    "ground_bounce": "ground_bounce",
    "prone": "prone",
    "prone_damage": "prone_damage",
    "getup": "getup",
    "getup_attack": "getup_attack",
    "getup_roll": "getup_roll",
    "knockdown": "knockdown",
    "tech": "tech",
    "tech_roll": "tech_roll",
    "wall_tech": "wall_tech",
    "wall_tech_jump": "wall_tech_jump",
    "ceiling_tech": "ceiling_tech",
    "shield_break_launch": "shield_break_launch",
    "shield_break_fall": "shield_break_fall",
    "shield_break_collapse": "shield_break_collapse",
    "shield_break_recover": "shield_break_recover",
    "dizzy": "dizzy",
    "sleep_start": "sleep_start",
    "sleep": "sleep",
    "wake": "wake",
    "bury_start": "bury_start",
    "buried": "buried",
    "bury_escape": "bury_escape",
    "footstool_jump": "footstool_jump",
    "footstooled": "stumble",
    "platform_drop": "platform_drop",
    "teeter_start": "teeter_start",
    "teeter": "teeter",
    "lose_footing": "stumble",
    "ledge_catch": "ledge_catch",
    "ledge_hang": "ledge_grab",
    "ledge_getup": "ledge_getup",
    "ledge_attack": "ledge_attack",
    "ledge_roll": "ledge_roll",
    "ledge_jump": "ledge_jump",
    "ledge_drop": "ledge_drop",
    "trip_fall": "trip_fall",
    "trip_land": "ground_bounce",
    "trip_idle": "trip_idle",
    "trip_getup": "trip_getup",
    "trip_attack": "trip_attack",
    "trip_roll": "trip_roll",
    "taunt": "taunt",
    "entrance": "entrance",
    "victory": "celebrate",
    "victory_hold": "victory_hold",
    "loss": "loss",
    "item_hold": "item_hold",
    "item_hold_crouch": "item_hold_crouch",
    "item_pickup": "item_pickup",
    "item_grip": "item_hold",
    "item_heavy_pickup": "item_heavy_pickup",
    "item_heavy_carry": "item_heavy_carry",
    "item_throw": "item_throw",
    "item_drop": "item_drop",
    "item_swing": "item_swing",
}


# Missing rows borrow the closest established Carl choreography. The alias is an
# implementation detail; semantic coverage remains the category map above.
POSE_ALIASES: Final[dict[str, str]] = {
    "idle_look_up": "think",
    "walk_stop": "land_recovery",
    "turnaround": "idle",
    "stumble": "hit",
    "crouch_start": "crouch",
    "crouch_end": "crouch",
    "land_light": "land_recovery",
    "jump_squat": "jump",
    "double_jump": "wall_jump",
    "fall_special": "float_glide",
    "tumble": "roll",
    "shield_raise": "block",
    "shield_release": "block",
    "parry": "block",
    "shield_hit": "hit",
    "spot_dodge": "roll",
    "roll_back": "roll",
    "air_dodge": "float_glide",
    "platform_drop": "fall",
    "footstool_jump": "jump",
    "teeter_start": "idle",
    "teeter": "idle",
    "launch": "fall",
    "meteor": "fall",
    "impact": "hit",
    "splat": "hit",
    "ground_bounce": "land_hard",
    "knockdown": "death",
    "prone": "death",
    "prone_damage": "hit",
    "getup": "land_recovery",
    "getup_attack": "planetary_orbit",
    "getup_roll": "roll",
    "tech": "land_recovery",
    "tech_roll": "roll",
    "wall_tech": "wall_grab",
    "wall_tech_jump": "wall_jump",
    "ceiling_tech": "land_recovery",
    "shield_break_launch": "hit",
    "shield_break_fall": "fall",
    "shield_break_collapse": "death",
    "shield_break_recover": "land_recovery",
    "dizzy": "think",
    "sleep_start": "death",
    "sleep": "death",
    "wake": "land_recovery",
    "bury_start": "crouch",
    "buried": "crouch",
    "bury_escape": "jump",
    "dash_attack": "planetary_orbit",
    "smash_charge": "think",
    "smash_forward": "planetary_orbit",
    "smash_up": "attack_up",
    "smash_down": "attack_down",
    "air_land": "land_recovery",
    "grab": "interact",
    "grab_hold": "use_telescope",
    "pummel": "jab",
    "grab_release": "interact",
    "throw_forward": "punch",
    "throw_back": "planetary_orbit",
    "throw_up": "attack_up",
    "throw_down": "attack_down",
    "grabbed": "hit",
    "grabbed_pummel": "hit",
    "grab_escape": "roll",
    "ledge_catch": "ledge_grab",
    "ledge_attack": "planetary_orbit",
    "ledge_jump": "wall_jump",
    "ledge_drop": "fall",
    "trip_fall": "death",
    "trip_idle": "death",
    "trip_getup": "land_recovery",
    "trip_attack": "planetary_orbit",
    "trip_roll": "roll",
    "item_hold": "use_telescope",
    "item_hold_crouch": "crouch",
    "item_pickup": "interact",
    "item_heavy_pickup": "interact",
    "item_heavy_carry": "walk",
    "item_throw": "punch",
    "item_drop": "interact",
    "item_swing": "planetary_orbit",
    "entrance": "stargaze",
    "victory_hold": "celebrate",
    "loss": "idle",
}


EFFECT_ALIASES: Final[dict[str, str]] = {
    # ⚠ no "idle_look_up" here. It used to borrow "think", which draws three
    # thought bubbles beside his head -- a leftover from when the POSE table
    # also aliased the row to "think". The pose is now idle with a raised
    # head, so the row is looking UP, not thinking, and it carries no effect.
    "shield_raise": "block",
    "shield_release": "block",
    "parry": "block",
    "dash_attack": "planetary_orbit",
    "smash_forward": "planetary_orbit",
    "smash_up": "attack_up",
    "smash_down": "attack_down",
    "getup_attack": "planetary_orbit",
    "ledge_attack": "planetary_orbit",
    "trip_attack": "planetary_orbit",
    "item_swing": "planetary_orbit",
    "entrance": "stargaze",
}


LOOPING_ROWS: Final[frozenset[str]] = frozenset(
    {
        "idle",
        "idle_look_up",
        "walk",
        "run",
        "fall",
        "fall_special",
        "teeter",
        "block",
        "prone",
        "dizzy",
        "sleep",
        "buried",
        "grab_hold",
        "grabbed",
        "ledge_grab",
        "climb",
        "swim",
        "float_glide",
        "item_hold",
        "item_hold_crouch",
        "item_heavy_carry",
        "victory_hold",
        "loss",
        "talk",
    }
)


__all__ = [
    "APPLICABLE_MOTION_SCOPES",
    "CARL_ROWS",
    "EFFECT_ALIASES",
    "FIGHTER_MOTION_COVERAGE",
    "LOOPING_ROWS",
    "POSE_ALIASES",
]
