"""Patent Clerk fighter-motion rows and canonical coverage map.

The long-term motion vocabulary lives in ``data/fighter_motion_vocabulary.yaml``.
This module is the deliberately smaller *current art* surface for Patent Clerk:
every applicable motion category resolves to an authored row, while variants
that do not yet deserve bespoke art share a representative row.

Keep this module data-only.  The native SVG rig builder imports ``PATENT_ROWS``
without importing the Patent Clerk renderer, avoiding a generated-rig cycle.
"""

from __future__ import annotations

from typing import Final

# Stable authored rows.  Existing bespoke names remain because they carry the
# character concept; generic fighter categories map to them below where that is
# the best current animation.
PATENT_ROWS: Final[tuple[tuple[str, int, int], ...]] = (
    # Stance / locomotion / traversal.
    ("idle", 8, 148),
    ("idle_look_up", 8, 150),
    ("walk", 8, 106),
    ("walk_stop", 6, 74),
    ("turnaround", 6, 72),
    ("dash_startup", 4, 50),
    ("dash", 6, 58),
    ("run", 8, 76),
    ("stumble", 6, 78),
    ("crouch_start", 5, 72),
    ("crouch", 6, 94),
    ("crouch_walk", 8, 90),
    ("crouch_end", 5, 72),
    ("land_light", 5, 66),
    ("land_hard", 7, 80),
    ("jump_squat", 5, 58),
    ("jump", 6, 88),
    ("double_jump", 7, 76),
    ("fall", 6, 92),
    ("fall_special", 7, 92),
    ("tumble", 8, 72),
    ("slide", 6, 68),
    ("roll", 8, 58),
    ("roll_back", 8, 58),
    ("spot_dodge", 7, 54),
    ("air_dodge", 7, 58),
    ("platform_drop", 5, 62),
    ("footstool_jump", 6, 68),
    ("teeter_start", 5, 72),
    ("teeter", 8, 94),
    # Defense / damage / recovery.
    ("shield_raise", 5, 62),
    ("block", 6, 80),
    ("shield_release", 5, 62),
    ("shield_hit", 5, 58),
    ("known_result", 7, 62),
    ("hit", 5, 82),
    ("launch", 7, 66),
    ("meteor", 7, 66),
    ("impact", 5, 66),
    ("splat", 8, 82),
    ("ground_bounce", 7, 72),
    ("knockdown", 6, 76),
    ("prone", 8, 110),
    ("prone_damage", 5, 72),
    ("getup", 8, 74),
    ("getup_attack", 8, 64),
    ("getup_roll", 8, 60),
    ("tech", 6, 56),
    ("tech_roll", 7, 56),
    ("wall_tech", 6, 62),
    ("wall_tech_jump", 7, 66),
    ("ceiling_tech", 6, 62),
    ("shield_break_launch", 7, 68),
    ("shield_break_fall", 7, 84),
    ("shield_break_collapse", 8, 82),
    ("shield_break_recover", 8, 86),
    ("dizzy", 10, 96),
    ("sleep_start", 7, 86),
    ("sleep", 10, 130),
    ("wake", 8, 86),
    ("bury_start", 7, 80),
    ("buried", 8, 108),
    ("bury_escape", 8, 72),
    # Normals / smashes / aerials.
    ("jab", 6, 54),
    ("dash_attack", 7, 60),
    ("attack_up", 8, 64),
    ("attack_down", 8, 64),
    ("smash_charge", 8, 84),
    ("smash_up", 9, 66),
    ("smash_down", 9, 68),
    ("air_neutral", 8, 62),
    ("air_forward", 7, 62),
    ("air_back", 7, 62),
    ("air_up", 7, 62),
    ("air_down", 7, 70),
    ("air_land", 6, 62),
    # Grab / throw / victim reactions.
    ("grab", 7, 62),
    ("grab_hold", 8, 92),
    ("pummel", 5, 58),
    ("grab_release", 5, 62),
    ("throw_forward", 8, 64),
    ("throw_back", 8, 66),
    ("throw_up", 8, 66),
    ("throw_down", 8, 68),
    ("grabbed", 8, 88),
    ("grabbed_pummel", 5, 62),
    ("grab_escape", 7, 66),
    # Ledge / wall / trip.
    ("wall_grab", 6, 102),
    ("wall_jump", 6, 80),
    ("ledge_catch", 5, 64),
    ("ledge_grab", 6, 96),
    ("ledge_getup", 7, 72),
    ("ledge_attack", 8, 66),
    ("ledge_roll", 8, 60),
    ("ledge_jump", 7, 68),
    ("ledge_drop", 5, 62),
    ("ledge_climb", 6, 92),
    ("climb", 8, 96),
    ("swim", 8, 102),
    # Generic held-item body motion. The item itself is supplied dynamically.
    ("item_hold", 8, 108),
    ("item_hold_crouch", 8, 96),
    ("item_pickup", 7, 70),
    ("item_heavy_pickup", 8, 82),
    ("item_heavy_carry", 8, 102),
    ("item_throw", 7, 62),
    ("item_drop", 5, 58),
    ("item_swing", 7, 62),
    # Presentation / interaction.
    ("entrance", 10, 88),
    ("victory_hold", 8, 118),
    ("loss", 8, 112),
    ("talk", 8, 104),
    ("interact", 8, 92),
    ("application_review", 6, 58),
    ("margin_correction", 7, 64),
    ("light_argument", 8, 66),
    ("reference_frame", 9, 72),
    ("elevator_thought", 9, 72),
    ("synchronize_clocks", 10, 78),
    ("mass_energy_conversion", 10, 80),
    ("annus_mirabilis", 12, 82),
    ("celebrate", 8, 88),
    ("taunt", 8, 92),
    ("death", 9, 102),
)

# Current-art coverage. Multiple categories intentionally share one row when
# the distinction is a future variation rather than a useful silhouette today.
FIGHTER_MOTION_COVERAGE: Final[dict[str, str]] = {
    "idle": "idle",
    "idle_look_up": "idle_look_up",
    "walk": "walk",
    "locomotion_stop": "walk_stop",
    "turnaround": "turnaround",
    "dash_startup": "dash_startup",
    "run": "run",
    "stumble": "stumble",
    "crouch_start": "crouch_start",
    "crouch": "crouch",
    "crouch_walk": "crouch_walk",
    # Covered by the plain jump until this fighter draws one of their own —
    # several categories resolving to one row is how the catalog keeps a slot
    # open without demanding the art up front.
    "crouch_jump": "jump",
    "crouch_end": "crouch_end",
    "land_light": "land_light",
    "land_hard": "land_hard",
    "jump_squat": "jump_squat",
    "jump": "jump",
    "double_jump": "double_jump",
    "fall": "fall",
    "fall_special": "fall_special",
    "land_special": "land_hard",
    "tumble": "tumble",
    "shield_raise": "shield_raise",
    "shield_hold": "block",
    "shield_release": "shield_release",
    "parry": "known_result",
    "shield_hit": "shield_hit",
    "spot_dodge": "spot_dodge",
    "roll_forward": "roll",
    "roll_backward": "roll_back",
    "air_dodge": "air_dodge",
    "jab": "jab",
    "dash_attack": "dash_attack",
    "attack_side": "margin_correction",
    "attack_up": "attack_up",
    "attack_down": "attack_down",
    "smash_charge_forward": "smash_charge",
    "smash_forward": "mass_energy_conversion",
    "smash_charge_up": "smash_charge",
    "smash_up": "smash_up",
    "smash_charge_down": "smash_charge",
    "smash_down": "smash_down",
    "air_neutral": "air_neutral",
    "air_forward": "air_forward",
    "air_back": "air_back",
    "air_up": "air_up",
    "air_down": "air_down",
    "air_land": "air_land",
    "special_neutral": "light_argument",
    "special_side": "reference_frame",
    "special_up": "elevator_thought",
    "special_down": "synchronize_clocks",
    "final_smash": "annus_mirabilis",
    "grab": "grab",
    "grab_hold": "grab_hold",
    "pummel": "pummel",
    "grab_release": "grab_release",
    "throw_forward": "throw_forward",
    "throw_back": "throw_back",
    "throw_up": "throw_up",
    "throw_down": "throw_down",
    "grabbed": "grabbed",
    "grabbed_pummel": "grabbed_pummel",
    "grab_escape": "grab_escape",
    "hit": "hit",
    "launch": "launch",
    "meteor": "meteor",
    "impact": "impact",
    "splat": "splat",
    "ground_bounce": "ground_bounce",
    "prone": "prone",
    "prone_damage": "prone_damage",
    "getup": "getup",
    "getup_attack": "getup_attack",
    "getup_roll": "getup_roll",
    "knockdown": "knockdown",
    "tech": "tech",
    "tech_roll": "tech_roll",
    "wall_tech": "wall_tech",
    "wall_tech_jump": "wall_tech_jump",
    "ceiling_tech": "ceiling_tech",
    "shield_break_launch": "shield_break_launch",
    "shield_break_fall": "shield_break_fall",
    "shield_break_collapse": "shield_break_collapse",
    "shield_break_recover": "shield_break_recover",
    "dizzy": "dizzy",
    "sleep_start": "sleep_start",
    "sleep": "sleep",
    "wake": "wake",
    "bury_start": "bury_start",
    "buried": "buried",
    "bury_escape": "bury_escape",
    "footstool_jump": "footstool_jump",
    "footstooled": "stumble",
    "platform_drop": "platform_drop",
    "teeter_start": "teeter_start",
    "teeter": "teeter",
    "lose_footing": "stumble",
    "ledge_catch": "ledge_catch",
    "ledge_hang": "ledge_grab",
    "ledge_getup": "ledge_getup",
    "ledge_attack": "ledge_attack",
    "ledge_roll": "ledge_roll",
    "ledge_jump": "ledge_jump",
    "ledge_drop": "ledge_drop",
    "trip_fall": "knockdown",
    "trip_land": "ground_bounce",
    "trip_idle": "prone",
    "trip_getup": "getup",
    "trip_attack": "getup_attack",
    "trip_roll": "getup_roll",
    "taunt": "taunt",
    "entrance": "entrance",
    "victory": "celebrate",
    "victory_hold": "victory_hold",
    "loss": "loss",
    # Generic dynamic-held-item categories.
    "item_hold": "item_hold",
    "item_hold_crouch": "item_hold_crouch",
    "item_pickup": "item_pickup",
    "item_grip": "item_hold",
    "item_heavy_pickup": "item_heavy_pickup",
    "item_heavy_carry": "item_heavy_carry",
    "item_throw": "item_throw",
    "item_drop": "item_drop",
    "item_swing": "item_swing",
}

APPLICABLE_MOTION_SCOPES: Final[tuple[str, ...]] = ("fighter_core", "generic_item")

# Fighter-facing standard categories can point at the character's bespoke
# visual language without duplicating the animation rows.
EFFECT_ALIASES: Final[dict[str, str]] = {
    "attack_side": "margin_correction",
    "smash_forward": "mass_energy_conversion",
    "special_neutral": "light_argument",
    "special_side": "reference_frame",
    "special_up": "elevator_thought",
    "special_down": "synchronize_clocks",
    "final_smash": "annus_mirabilis",
    "parry": "known_result",
}

__all__ = [
    "APPLICABLE_MOTION_SCOPES",
    "EFFECT_ALIASES",
    "FIGHTER_MOTION_COVERAGE",
    "PATENT_ROWS",
]
