"""Perfect Cellular Automaton fighter-motion coverage.

PCA already has a hand-authored SVG rig and a substantial action set. This file
adds the same current-art fighter contract used by the other full fighters while
preserving PCA's authored clips as the source choreography. Missing semantic
rows borrow an established PCA pose until bespoke art is justified.
"""

from __future__ import annotations

from typing import Final


APPLICABLE_MOTION_SCOPES: Final[tuple[str, ...]] = (
    "fighter_core",
    "generic_item",
)


PCA_ROWS: Final[tuple[tuple[str, int, int], ...]] = (
    # Existing authored motion surface.
    ("idle", 10, 120),
    ("idle_look_up", 8, 120),
    ("walk", 8, 90),
    ("walk_stop", 6, 72),
    ("turnaround", 6, 72),
    ("dash_startup", 4, 40),
    ("dash", 5, 38),
    ("run", 8, 70),
    ("stumble", 6, 72),
    ("crouch_start", 5, 68),
    ("crouch", 1, 100),
    ("crouch_walk", 8, 110),
    ("crouch_end", 5, 68),
    ("land_light", 5, 60),
    ("land_hard", 5, 55),
    ("land_recovery", 5, 60),
    ("jump_squat", 5, 55),
    ("jump", 6, 70),
    ("double_jump", 7, 68),
    ("fall", 4, 120),
    ("fall_special", 7, 92),
    ("tumble", 8, 70),
    ("slide", 5, 60),
    ("roll", 6, 42),
    ("roll_back", 6, 42),
    ("spot_dodge", 7, 52),
    ("air_dodge", 7, 58),
    ("platform_drop", 5, 60),
    ("footstool_jump", 6, 66),
    ("teeter_start", 5, 68),
    ("teeter", 8, 92),
    # Defense / damage / recovery.
    ("block", 1, 100),
    ("shield_raise", 5, 58),
    ("shield_release", 5, 58),
    ("parry", 6, 56),
    ("shield_hit", 5, 56),
    ("hit", 5, 48),
    ("launch", 7, 64),
    ("meteor", 7, 64),
    ("impact", 5, 60),
    ("splat", 8, 78),
    ("ground_bounce", 7, 68),
    ("knockdown", 7, 74),
    ("prone", 8, 104),
    ("prone_damage", 5, 68),
    ("getup", 8, 70),
    ("getup_attack", 7, 52),
    ("getup_roll", 7, 52),
    ("tech", 6, 52),
    ("tech_roll", 7, 52),
    ("wall_tech", 6, 58),
    ("wall_tech_jump", 6, 50),
    ("ceiling_tech", 6, 58),
    ("shield_break_launch", 7, 64),
    ("shield_break_fall", 7, 80),
    ("shield_break_collapse", 8, 78),
    ("shield_break_recover", 8, 82),
    ("dizzy", 10, 92),
    ("sleep_start", 7, 82),
    ("sleep", 8, 126),
    ("wake", 8, 82),
    ("bury_start", 7, 76),
    ("buried", 8, 102),
    ("bury_escape", 8, 68),
    # Normals / smashes / aerials.
    ("jab", 5, 45),
    ("punch", 6, 55),
    ("slash", 7, 52),
    ("dash_attack", 7, 56),
    ("attack_side", 6, 48),
    ("attack_up", 6, 48),
    ("attack_down", 6, 48),
    ("smash_charge", 8, 82),
    ("smash_forward", 8, 60),
    ("smash_up", 8, 60),
    ("smash_down", 8, 62),
    ("air_neutral", 6, 52),
    ("air_forward", 6, 52),
    ("air_back", 6, 52),
    ("air_up", 6, 52),
    ("air_down", 6, 52),
    ("air_land", 6, 60),
    # PCA-specific abilities used as the Smash special slots.
    ("shoot", 6, 58),
    ("special", 10, 70),
    ("charge", 8, 90),
    ("fly", 8, 130),
    ("hover", 8, 130),
    ("float_glide", 8, 130),
    ("final_smash", 12, 70),
    ("blink_out", 5, 42),
    ("blink_in", 5, 42),
    # Grab / throw / victim reactions.
    ("grab", 7, 58),
    ("grab_hold", 8, 88),
    ("pummel", 5, 54),
    ("grab_release", 5, 58),
    ("throw_forward", 8, 60),
    ("throw_back", 8, 62),
    ("throw_up", 8, 62),
    ("throw_down", 8, 64),
    ("grabbed", 8, 84),
    ("grabbed_pummel", 5, 58),
    ("grab_escape", 7, 62),
    # Wall / ledge / trip.
    ("wall_grab", 6, 150),
    ("wall_jump", 6, 50),
    ("ledge_catch", 5, 60),
    ("ledge_grab", 6, 150),
    ("ledge_climb", 7, 60),
    ("ledge_getup", 6, 60),
    ("ledge_attack", 7, 52),
    ("ledge_roll", 7, 48),
    ("ledge_jump", 7, 64),
    ("ledge_drop", 5, 58),
    ("ledge_getup_attack", 7, 52),
    ("ladder_climb", 8, 120),
    ("swim", 8, 120),
    ("trip_fall", 7, 70),
    ("trip_idle", 8, 102),
    ("trip_getup", 8, 70),
    ("trip_attack", 7, 52),
    ("trip_roll", 7, 52),
    # Generic dynamic-item body motion.
    ("item_hold", 8, 100),
    ("item_hold_crouch", 8, 92),
    ("item_pickup", 7, 68),
    ("item_heavy_pickup", 8, 78),
    ("item_heavy_carry", 8, 98),
    ("item_throw", 7, 60),
    ("item_drop", 5, 54),
    ("item_swing", 7, 58),
    # Existing presentation / interaction.
    ("aim", 6, 130),
    ("taunt", 8, 150),
    ("talk", 8, 140),
    ("interact", 6, 80),
    ("entrance", 8, 70),
    ("victory", 8, 100),
    ("victory_hold", 8, 120),
    ("loss", 8, 110),
    ("death", 8, 85),
)


FIGHTER_MOTION_COVERAGE: Final[dict[str, str]] = {
    "idle": "idle",
    "idle_look_up": "idle_look_up",
    "walk": "walk",
    "locomotion_stop": "walk_stop",
    "turnaround": "turnaround",
    "dash_startup": "dash_startup",
    "run": "run",
    "stumble": "stumble",
    "crouch_start": "crouch_start",
    "crouch": "crouch",
    "crouch_walk": "crouch_walk",
    # Covered by the plain jump until this fighter draws one of their own —
    # several categories resolving to one row is how the catalog keeps a slot
    # open without demanding the art up front.
    "crouch_jump": "jump",
    "crouch_end": "crouch_end",
    "land_light": "land_light",
    "land_hard": "land_hard",
    "jump_squat": "jump_squat",
    "jump": "jump",
    "double_jump": "double_jump",
    "fall": "fall",
    "fall_special": "fall_special",
    "land_special": "land_hard",
    "tumble": "tumble",
    "shield_raise": "shield_raise",
    "shield_hold": "block",
    "shield_release": "shield_release",
    "parry": "parry",
    "shield_hit": "shield_hit",
    "spot_dodge": "spot_dodge",
    "roll_forward": "roll",
    "roll_backward": "roll_back",
    "air_dodge": "air_dodge",
    "jab": "jab",
    "dash_attack": "dash_attack",
    "attack_side": "attack_side",
    "attack_up": "attack_up",
    "attack_down": "attack_down",
    "smash_charge_forward": "smash_charge",
    "smash_forward": "smash_forward",
    "smash_charge_up": "smash_charge",
    "smash_up": "smash_up",
    "smash_charge_down": "smash_charge",
    "smash_down": "smash_down",
    "air_neutral": "air_neutral",
    "air_forward": "air_forward",
    "air_back": "air_back",
    "air_up": "air_up",
    "air_down": "air_down",
    "air_land": "air_land",
    "special_neutral": "shoot",
    "special_side": "special",
    "special_up": "fly",
    "special_down": "charge",
    "final_smash": "final_smash",
    "grab": "grab",
    "grab_hold": "grab_hold",
    "pummel": "pummel",
    "grab_release": "grab_release",
    "throw_forward": "throw_forward",
    "throw_back": "throw_back",
    "throw_up": "throw_up",
    "throw_down": "throw_down",
    "grabbed": "grabbed",
    "grabbed_pummel": "grabbed_pummel",
    "grab_escape": "grab_escape",
    "hit": "hit",
    "launch": "launch",
    "meteor": "meteor",
    "impact": "impact",
    "splat": "splat",
    "ground_bounce": "ground_bounce",
    "prone": "prone",
    "prone_damage": "prone_damage",
    "getup": "getup",
    "getup_attack": "getup_attack",
    "getup_roll": "getup_roll",
    "knockdown": "knockdown",
    "tech": "tech",
    "tech_roll": "tech_roll",
    "wall_tech": "wall_tech",
    "wall_tech_jump": "wall_tech_jump",
    "ceiling_tech": "ceiling_tech",
    "shield_break_launch": "shield_break_launch",
    "shield_break_fall": "shield_break_fall",
    "shield_break_collapse": "shield_break_collapse",
    "shield_break_recover": "shield_break_recover",
    "dizzy": "dizzy",
    "sleep_start": "sleep_start",
    "sleep": "sleep",
    "wake": "wake",
    "bury_start": "bury_start",
    "buried": "buried",
    "bury_escape": "bury_escape",
    "footstool_jump": "footstool_jump",
    "footstooled": "stumble",
    "platform_drop": "platform_drop",
    "teeter_start": "teeter_start",
    "teeter": "teeter",
    "lose_footing": "stumble",
    "ledge_catch": "ledge_catch",
    "ledge_hang": "ledge_grab",
    "ledge_getup": "ledge_getup",
    "ledge_attack": "ledge_attack",
    "ledge_roll": "ledge_roll",
    "ledge_jump": "ledge_jump",
    "ledge_drop": "ledge_drop",
    "trip_fall": "trip_fall",
    "trip_land": "ground_bounce",
    "trip_idle": "trip_idle",
    "trip_getup": "trip_getup",
    "trip_attack": "trip_attack",
    "trip_roll": "trip_roll",
    "taunt": "taunt",
    "entrance": "entrance",
    "victory": "victory",
    "victory_hold": "victory_hold",
    "loss": "loss",
    "item_hold": "item_hold",
    "item_hold_crouch": "item_hold_crouch",
    "item_pickup": "item_pickup",
    "item_grip": "item_hold",
    "item_heavy_pickup": "item_heavy_pickup",
    "item_heavy_carry": "item_heavy_carry",
    "item_throw": "item_throw",
    "item_drop": "item_drop",
    "item_swing": "item_swing",
}


POSE_ALIASES: Final[dict[str, str]] = {
    "idle_look_up": "idle",
    "walk_stop": "land_recovery",
    "turnaround": "idle",
    "stumble": "hit",
    "crouch_start": "crouch",
    "crouch_end": "crouch",
    "land_light": "land_recovery",
    "jump_squat": "jump",
    "double_jump": "wall_jump",
    "fall_special": "float_glide",
    "tumble": "roll",
    "shield_raise": "block",
    "shield_release": "block",
    "parry": "block",
    "shield_hit": "hit",
    "spot_dodge": "roll",
    "roll_back": "roll",
    "air_dodge": "float_glide",
    "platform_drop": "fall",
    "footstool_jump": "jump",
    "teeter_start": "idle",
    "teeter": "idle",
    "launch": "fall",
    "meteor": "fall",
    "impact": "hit",
    "splat": "hit",
    "ground_bounce": "land_hard",
    "knockdown": "death",
    "prone": "death",
    "prone_damage": "hit",
    "getup": "land_recovery",
    "getup_attack": "ledge_getup_attack",
    "getup_roll": "roll",
    "tech": "land_recovery",
    "tech_roll": "roll",
    "wall_tech": "wall_grab",
    "wall_tech_jump": "wall_jump",
    "ceiling_tech": "land_recovery",
    "shield_break_launch": "hit",
    "shield_break_fall": "fall",
    "shield_break_collapse": "death",
    "shield_break_recover": "land_recovery",
    "dizzy": "idle",
    "sleep_start": "death",
    "sleep": "death",
    "wake": "land_recovery",
    "bury_start": "crouch",
    "buried": "crouch",
    "bury_escape": "jump",
    "dash_attack": "attack_side",
    "smash_charge": "charge",
    "smash_forward": "punch",
    "smash_up": "attack_up",
    "smash_down": "attack_down",
    "air_land": "land_recovery",
    "final_smash": "special",
    "grab": "interact",
    "grab_hold": "aim",
    "pummel": "jab",
    "grab_release": "interact",
    "throw_forward": "punch",
    "throw_back": "attack_side",
    "throw_up": "attack_up",
    "throw_down": "attack_down",
    "grabbed": "hit",
    "grabbed_pummel": "hit",
    "grab_escape": "roll",
    "ledge_catch": "ledge_grab",
    "ledge_attack": "ledge_getup_attack",
    "ledge_jump": "wall_jump",
    "ledge_drop": "fall",
    "trip_fall": "death",
    "trip_idle": "death",
    "trip_getup": "land_recovery",
    "trip_attack": "ledge_getup_attack",
    "trip_roll": "roll",
    "item_hold": "aim",
    "item_hold_crouch": "crouch",
    "item_pickup": "interact",
    "item_heavy_pickup": "interact",
    "item_heavy_carry": "walk",
    "item_throw": "punch",
    "item_drop": "interact",
    "item_swing": "slash",
    "entrance": "blink_in",
    "victory": "taunt",
    "victory_hold": "taunt",
    "loss": "idle",
}


PCA_ANIMATION_BINDINGS: Final[dict[str, dict[str, object]]] = {
    "default": {"animation": "idle", "events": []},
    "locomotion.walk": {"animation": "walk", "events": []},
    "locomotion.run": {"animation": "run", "events": []},
    "traversal.jump": {"animation": "jump", "events": []},
    "traversal.fall": {"animation": "fall", "events": []},
    "action.melee.primary": {"animation": "attack_side", "events": []},
    "action.ranged.primary": {"animation": "shoot", "events": []},
    "action.special.primary": {"animation": "special", "events": []},
    "action.special.up": {"animation": "fly", "events": []},
    "action.special.down": {"animation": "charge", "events": []},
    "action.super": {"animation": "final_smash", "events": []},
    "action.defense.block": {"animation": "block", "events": []},
    "action.defense.roll": {"animation": "roll", "events": []},
    "interaction.use": {"animation": "interact", "events": []},
    "emote.taunt": {"animation": "taunt", "events": []},
}


LOOPING_ROWS: Final[frozenset[str]] = frozenset(
    {
        "idle",
        "idle_look_up",
        "walk",
        "run",
        "fall",
        "fall_special",
        "teeter",
        "block",
        "prone",
        "dizzy",
        "sleep",
        "buried",
        "grab_hold",
        "grabbed",
        "ledge_grab",
        "ladder_climb",
        "swim",
        "fly",
        "hover",
        "float_glide",
        "charge",
        "item_hold",
        "item_hold_crouch",
        "item_heavy_carry",
        "victory_hold",
        "loss",
        "aim",
        "talk",
    }
)


__all__ = [
    "APPLICABLE_MOTION_SCOPES",
    "FIGHTER_MOTION_COVERAGE",
    "LOOPING_ROWS",
    "PCA_ANIMATION_BINDINGS",
    "PCA_ROWS",
    "POSE_ALIASES",
]
