"""Player Robot v3 fighter-motion rows and current-art coverage.

The long-term motion vocabulary lives in ``data/fighter_motion_vocabulary.yaml``.
This module is the robot's current visual contract: every applicable fighter
category resolves to a real published row, while future left/right, grounded /
aerial, and reaction variants may intentionally share that row.

Keep this module data-only. Both the SVG rig builder and the shipping target
import it, so row generation, sheet publication, and coverage validation cannot
drift apart.
"""

from __future__ import annotations

from typing import Final


APPLICABLE_MOTION_SCOPES: Final[tuple[str, ...]] = (
    "fighter_core",
    "generic_item",
)


ROBOT_ROWS: Final[tuple[tuple[str, int, int], ...]] = (
    # Stance / locomotion / traversal.
    ("idle", 8, 120),
    ("idle_look_up", 8, 120),
    ("walk", 8, 95),
    ("walk_stop", 6, 72),
    ("turnaround", 6, 72),
    ("dash_startup", 4, 50),
    ("dash", 6, 65),
    ("run", 8, 75),
    ("stumble", 6, 74),
    ("crouch_start", 5, 68),
    ("crouch", 6, 95),
    ("crouch_walk", 8, 88),
    # A crouch that leaves the ground. Nothing in the vocabulary could name one
    # until `CharacterAnim::CrouchJump` existed, so a ducked jump drew a plain
    # one; the row falls back to `jump` for a sheet that skips it.
    ("crouch_jump", 3, 90),
    ("crouch_end", 5, 68),
    ("land", 6, 72),
    ("land_hard", 8, 95),
    ("land_recovery", 6, 82),
    ("jump_squat", 5, 55),
    ("jump", 6, 95),
    ("double_jump", 7, 74),
    ("fall", 6, 95),
    ("fall_special", 7, 92),
    ("tumble", 8, 72),
    ("slide", 6, 70),
    ("roll", 8, 58),
    ("roll_back", 8, 58),
    ("spot_dodge", 7, 54),
    ("air_dodge", 7, 58),
    ("platform_drop", 5, 60),
    ("footstool_jump", 6, 66),
    ("teeter_start", 5, 70),
    ("teeter", 8, 92),
    # Defense / damage / recovery.
    ("shield_raise", 5, 60),
    ("block", 6, 85),
    ("shield_release", 5, 60),
    ("parry", 6, 58),
    ("shield_hit", 5, 58),
    ("hit", 5, 90),
    ("launch", 7, 66),
    ("meteor", 7, 66),
    ("impact", 5, 64),
    ("splat", 8, 80),
    ("ground_bounce", 7, 70),
    ("knockdown", 7, 76),
    ("prone", 8, 108),
    ("prone_damage", 5, 70),
    ("getup", 8, 72),
    ("getup_attack", 8, 62),
    ("getup_roll", 8, 58),
    ("tech", 6, 54),
    ("tech_roll", 7, 54),
    ("wall_tech", 6, 60),
    ("wall_tech_jump", 7, 64),
    ("ceiling_tech", 6, 60),
    ("shield_break_launch", 7, 66),
    ("shield_break_fall", 7, 82),
    ("shield_break_collapse", 8, 80),
    ("shield_break_recover", 8, 84),
    ("dizzy", 10, 94),
    ("sleep_start", 7, 84),
    ("sleep", 8, 130),
    ("wake", 8, 84),
    ("bury_start", 7, 78),
    ("buried", 8, 106),
    ("bury_escape", 8, 70),
    # Normals / smashes / aerials.
    ("slash", 8, 75),
    ("jab", 6, 52),
    ("dash_attack", 7, 58),
    ("attack_side", 3, 60),
    ("attack_up", 3, 60),
    ("attack_down", 3, 60),
    ("smash_charge", 8, 76),
    ("smash_forward", 8, 62),
    ("smash_up", 8, 62),
    ("smash_down", 8, 64),
    ("air_neutral", 3, 60),
    ("air_forward", 3, 60),
    ("air_back", 3, 60),
    ("air_down", 3, 60),
    ("air_up", 3, 60),
    ("air_land", 6, 62),
    # Robot-specific / Ambition abilities used as Smash specials.
    ("shoot", 6, 58),
    ("blink_out", 6, 62),
    ("blink_in", 6, 62),
    ("hover", 8, 78),
    ("float_glide", 8, 82),
    ("charge", 8, 76),
    ("final_smash", 12, 72),
    # Grab / throw / victim reactions.
    ("grab", 7, 60),
    ("grab_hold", 8, 90),
    ("pummel", 5, 56),
    ("grab_release", 5, 60),
    ("throw_forward", 8, 62),
    ("throw_back", 8, 64),
    ("throw_up", 8, 64),
    ("throw_down", 8, 66),
    ("grabbed", 8, 86),
    ("grabbed_pummel", 5, 60),
    ("grab_escape", 7, 64),
    # Wall / ledge / trip.
    ("wall_grab", 6, 95),
    ("wall_jump", 6, 85),
    ("ledge_catch", 5, 62),
    ("ledge_grab", 6, 100),
    ("ledge_getup", 6, 92),
    ("ledge_attack", 8, 64),
    ("ledge_roll", 8, 40),
    ("ledge_jump", 7, 66),
    ("ledge_drop", 5, 60),
    ("ledge_climb", 6, 92),
    ("climb", 8, 100),
    ("swim", 8, 105),
    ("trip_fall", 7, 72),
    ("trip_idle", 8, 106),
    ("trip_getup", 8, 72),
    ("trip_attack", 8, 62),
    ("trip_roll", 8, 58),
    # Generic held-item body motion. Items remain dynamically supplied.
    ("item_hold", 8, 104),
    ("item_hold_crouch", 8, 94),
    ("pickup", 7, 82),
    ("item_heavy_pickup", 8, 80),
    ("item_heavy_carry", 8, 100),
    ("throw", 7, 72),
    ("item_drop", 5, 56),
    ("item_swing", 7, 60),
    # Presentation / interaction and retained Ambition rows.
    ("taunt", 8, 90),
    ("entrance", 8, 72),
    ("celebrate", 8, 92),
    ("victory_hold", 8, 114),
    ("loss", 8, 110),
    ("aim", 6, 100),
    ("interact", 6, 90),
    ("talk", 8, 110),
    ("death", 8, 110),
)


# Current-art category coverage. Fine-grained future slots remain in the shared
# vocabulary and can split later without changing this category contract.
FIGHTER_MOTION_COVERAGE: Final[dict[str, str]] = {
    "idle": "idle",
    "idle_look_up": "idle_look_up",
    "walk": "walk",
    "locomotion_stop": "walk_stop",
    "turnaround": "turnaround",
    "dash_startup": "dash_startup",
    "run": "run",
    "stumble": "stumble",
    "crouch_start": "crouch_start",
    "crouch": "crouch",
    "crouch_walk": "crouch_walk",
    "crouch_jump": "crouch_jump",
    "crouch_end": "crouch_end",
    "land_light": "land",
    "land_hard": "land_hard",
    "jump_squat": "jump_squat",
    "jump": "jump",
    "double_jump": "double_jump",
    "fall": "fall",
    "fall_special": "fall_special",
    "land_special": "land_hard",
    "tumble": "tumble",
    "shield_raise": "shield_raise",
    "shield_hold": "block",
    "shield_release": "shield_release",
    "parry": "parry",
    "shield_hit": "shield_hit",
    "spot_dodge": "spot_dodge",
    "roll_forward": "roll",
    "roll_backward": "roll_back",
    "air_dodge": "air_dodge",
    "jab": "jab",
    "dash_attack": "dash_attack",
    "attack_side": "attack_side",
    "attack_up": "attack_up",
    "attack_down": "attack_down",
    "smash_charge_forward": "smash_charge",
    "smash_forward": "smash_forward",
    "smash_charge_up": "smash_charge",
    "smash_up": "smash_up",
    "smash_charge_down": "smash_charge",
    "smash_down": "smash_down",
    "air_neutral": "air_neutral",
    "air_forward": "air_forward",
    "air_back": "air_back",
    "air_up": "air_up",
    "air_down": "air_down",
    "air_land": "air_land",
    "special_neutral": "shoot",
    "special_side": "blink_out",
    "special_up": "hover",
    "special_down": "charge",
    "final_smash": "final_smash",
    "grab": "grab",
    "grab_hold": "grab_hold",
    "pummel": "pummel",
    "grab_release": "grab_release",
    "throw_forward": "throw_forward",
    "throw_back": "throw_back",
    "throw_up": "throw_up",
    "throw_down": "throw_down",
    "grabbed": "grabbed",
    "grabbed_pummel": "grabbed_pummel",
    "grab_escape": "grab_escape",
    "hit": "hit",
    "launch": "launch",
    "meteor": "meteor",
    "impact": "impact",
    "splat": "splat",
    "ground_bounce": "ground_bounce",
    "prone": "prone",
    "prone_damage": "prone_damage",
    "getup": "getup",
    "getup_attack": "getup_attack",
    "getup_roll": "getup_roll",
    "knockdown": "knockdown",
    "tech": "tech",
    "tech_roll": "tech_roll",
    "wall_tech": "wall_tech",
    "wall_tech_jump": "wall_tech_jump",
    "ceiling_tech": "ceiling_tech",
    "shield_break_launch": "shield_break_launch",
    "shield_break_fall": "shield_break_fall",
    "shield_break_collapse": "shield_break_collapse",
    "shield_break_recover": "shield_break_recover",
    "dizzy": "dizzy",
    "sleep_start": "sleep_start",
    "sleep": "sleep",
    "wake": "wake",
    "bury_start": "bury_start",
    "buried": "buried",
    "bury_escape": "bury_escape",
    "footstool_jump": "footstool_jump",
    "footstooled": "stumble",
    "platform_drop": "platform_drop",
    "teeter_start": "teeter_start",
    "teeter": "teeter",
    "lose_footing": "stumble",
    "ledge_catch": "ledge_catch",
    "ledge_hang": "ledge_grab",
    "ledge_getup": "ledge_getup",
    "ledge_attack": "ledge_attack",
    "ledge_roll": "ledge_roll",
    "ledge_jump": "ledge_jump",
    "ledge_drop": "ledge_drop",
    "trip_fall": "trip_fall",
    "trip_land": "ground_bounce",
    "trip_idle": "trip_idle",
    "trip_getup": "trip_getup",
    "trip_attack": "trip_attack",
    "trip_roll": "trip_roll",
    "taunt": "taunt",
    "entrance": "entrance",
    "victory": "celebrate",
    "victory_hold": "victory_hold",
    "loss": "loss",
    "item_hold": "item_hold",
    "item_hold_crouch": "item_hold_crouch",
    "item_pickup": "pickup",
    "item_grip": "item_hold",
    "item_heavy_pickup": "item_heavy_pickup",
    "item_heavy_carry": "item_heavy_carry",
    "item_throw": "throw",
    "item_drop": "item_drop",
    "item_swing": "item_swing",
}


# Rows not yet given bespoke robot choreography borrow an established source
# motion and are then adjusted by the v3 builder where the category needs a
# distinct silhouette. This is an authoring implementation detail, not a claim
# that the categories are semantically identical.
POSE_ALIASES: Final[dict[str, str]] = {
    "idle_look_up": "idle",
    "walk_stop": "land_recovery",
    "turnaround": "idle",
    "stumble": "hit",
    "crouch_start": "crouch",
    "crouch_end": "crouch",
    "land": "land",
    "jump_squat": "jump",
    "double_jump": "wall_jump",
    "fall_special": "float_glide",
    "tumble": "roll",
    "shield_raise": "block",
    "shield_release": "block",
    "parry": "block",
    "shield_hit": "hit",
    "spot_dodge": "roll",
    "roll_back": "roll",
    "air_dodge": "float_glide",
    "platform_drop": "fall",
    "footstool_jump": "jump",
    "teeter_start": "idle",
    "teeter": "idle",
    "launch": "fall",
    "meteor": "fall",
    "impact": "hit",
    "splat": "hit",
    "ground_bounce": "land_hard",
    "knockdown": "death",
    "prone": "death",
    "prone_damage": "hit",
    "getup": "land_recovery",
    "getup_attack": "ledge_getup_attack",
    "getup_roll": "roll",
    "tech": "land",
    "tech_roll": "roll",
    "wall_tech": "wall_grab",
    "wall_tech_jump": "wall_jump",
    "ceiling_tech": "land",
    "shield_break_launch": "hit",
    "shield_break_fall": "fall",
    "shield_break_collapse": "death",
    "shield_break_recover": "land_recovery",
    "dizzy": "idle",
    "sleep_start": "sleep",
    "wake": "sleep",
    "bury_start": "crouch",
    "buried": "crouch",
    "bury_escape": "jump",
    "jab": "attack_side",
    "dash_attack": "attack_side",
    "smash_charge": "charge",
    "smash_forward": "attack_side",
    "smash_up": "attack_up",
    "smash_down": "attack_down",
    "air_land": "land",
    "final_smash": "charge",
    "grab": "interact",
    "grab_hold": "aim",
    "pummel": "attack_down",
    "grab_release": "interact",
    "throw_forward": "throw",
    "throw_back": "throw",
    "throw_up": "throw",
    "throw_down": "throw",
    "grabbed": "hit",
    "grabbed_pummel": "hit",
    "grab_escape": "roll",
    "ledge_catch": "ledge_grab",
    "ledge_attack": "ledge_getup_attack",
    "ledge_jump": "wall_jump",
    "ledge_drop": "fall",
    "trip_fall": "death",
    "trip_idle": "death",
    "trip_getup": "land_recovery",
    "trip_attack": "ledge_getup_attack",
    "trip_roll": "roll",
    "item_hold": "aim",
    "item_hold_crouch": "crouch",
    "item_heavy_pickup": "pickup",
    "item_heavy_carry": "walk",
    "item_drop": "pickup",
    "item_swing": "slash",
    "taunt": "celebrate",
    "entrance": "blink_in",
    "victory_hold": "celebrate",
    "loss": "idle",
}


# Effects are attached to the visual source action while solving remains on the
# actual motion row. This keeps, e.g., smash-forward's blade arc and fall-
# special's boot jets without pretending those rows are the same animation.
EFFECT_ALIASES: Final[dict[str, str]] = {
    "jab": "attack_side",
    "dash_attack": "attack_side",
    "smash_charge": "charge",
    "smash_forward": "attack_side",
    "smash_up": "attack_up",
    "smash_down": "attack_down",
    "fall_special": "float_glide",
    "shield_raise": "block",
    "shield_release": "block",
    "parry": "block",
    "shield_hit": "hit",
    "getup_attack": "ledge_getup_attack",
    "ledge_attack": "ledge_getup_attack",
    "trip_attack": "ledge_getup_attack",
    "final_smash": "charge",
    "entrance": "blink_in",
}


LOOPING_ROWS: Final[frozenset[str]] = frozenset(
    {
        "idle",
        "idle_look_up",
        "walk",
        "run",
        "fall",
        "fall_special",
        "teeter",
        "block",
        "prone",
        "dizzy",
        "sleep",
        "buried",
        "grab_hold",
        "grabbed",
        "ledge_grab",
        "climb",
        "swim",
        "item_hold",
        "item_hold_crouch",
        "item_heavy_carry",
        "victory_hold",
        "loss",
        "aim",
        "hover",
        "float_glide",
        "charge",
        "talk",
    }
)


__all__ = [
    "APPLICABLE_MOTION_SCOPES",
    "EFFECT_ALIASES",
    "FIGHTER_MOTION_COVERAGE",
    "LOOPING_ROWS",
    "POSE_ALIASES",
    "ROBOT_ROWS",
]
