target: goblin
name: goblin_desert_bow
seed: 85
archetype: desert_scout
held_item: bow
variant: desert_bow_scout
animations:
- idle
- walk
- run
- slash
- dash
- hit
- death
render:
  frame_width: 128
  frame_height: 128
  single_width: 128
  single_height: 128
  supersample: 1
  downsample: lanczos
  background: transparent
  sheet_background: transparent
  border: 0
  label_width: 132
  crop: true
actor:
  character_id: npc_goblin_desert_bow
  display_name: Goblin Desert Bow
visual:
  default_pose: idle
body:
  body_plan: HumanoidBiped
  body_kind: Standard
  mass_class: Medium
  traits:
  - story
  - humanoid
  - enemy
  - combatant
  - ranged
  - goblin
  - desert
  - bow
  locomotion_hint: Walk
capabilities:
  traversal:
    walk: true
    jump: null
    climb: null
    fly: null
    swim: null
    crawl: null
    use_lifts: true
    door_access:
    - public
  interactions:
    talk: true
    trade: null
    carry: null
    open_doors:
    - public
brain:
  default_preset: skirmisher_ranger
actions:
  default_preset: ranger_arrow
animation_bindings:
  default:
    animation: idle
    events: []
  locomotion.walk:
    animation: walk
    events: []
  interaction.talk:
    animation: talk
    events: []
  interaction.use:
    animation: interact
    events: []
  action.melee.primary:
    animation: slash
    events:
    - t: 0.34
      event: hitbox_active_start
      source: explicit.profile.combat_humanoid
    - t: 0.58
      event: hitbox_active_end
      source: explicit.profile.combat_humanoid
  action.ranged.primary:
    animation: slash
    events:
    - t: 0.5
      event: projectile_release
      source: explicit.profile.ranged_humanoid
sockets:
  head:
    source: explicit.profile.humanoid
    point:
      x: 64.0
      y: 24.0
  chest:
    source: explicit.profile.humanoid
    point:
      x: 64.0
      y: 54.0
  hand_l:
    source: explicit.profile.humanoid
    point:
      x: 48.0
      y: 64.0
  hand_r:
    source: explicit.profile.humanoid
    point:
      x: 80.0
      y: 64.0
  speech_bubble:
    source: explicit.profile.humanoid
    point:
      x: 64.0
      y: 8.0
  weapon_grip:
    source: explicit.profile.combat_humanoid
    point:
      x: 80.0
      y: 64.0
  weapon_tip:
    source: explicit.profile.combat_humanoid
    point:
      x: 104.0
      y: 60.0
  muzzle:
    source: explicit.profile.ranged_humanoid
    point:
      x: 96.0
      y: 58.0
  projectile_origin:
    source: explicit.profile.ranged_humanoid
    point:
      x: 96.0
      y: 58.0
tags:
- story
- humanoid
- enemy
- combatant
- ranged
- goblin
- desert
- bow
